## Numpy

## Task 1:

In [10]:
import numpy as np;

In [11]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]]);

In [12]:
print(a);

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [13]:
mean_a = a.mean(axis=0);

In [14]:
print(mean_a);

[2.  8.4]


## Task 2:

In [16]:
a_centered = a - mean_a;

In [17]:
print(a_centered);

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


## Task 3:

In [21]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1]);

In [22]:
print(a_centered_sp);

8.0


In [60]:
N = len(a_centered[:,0])

In [57]:
res = a_centered_sp / (N - 1)

In [59]:
print(res)

2.0


## Task 4:

In [62]:
a_t = a.T

In [63]:
a_t

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [65]:
covariant_matrix = np.cov(a_t)

In [66]:
result = covariant_matrix[0][1]

In [67]:
print(result)

2.0


## Pandas

## Task 1

In [68]:
import pandas as pd

In [69]:
authors = pd.DataFrame({"author_id": [1, 2, 3] , "author_name":['Тургенев', 'Чехов', 'Островский']})

In [70]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [71]:
book = pd.DataFrame({"author_id": [1, 1, 1, 2, 2, 3, 3], "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], "price": [450, 300, 350, 500, 450, 370, 290]})

In [72]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Task 2

In [97]:
authors_price = pd.merge(authors, book, on="author_id", how="outer")

In [98]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Task 3

In [80]:
top5 = authors_price.sort_values(by="price", ascending=False)

In [82]:
top5.head(5)

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Task 4

In [107]:
 authors_stat = authors_price.groupby("author_name").agg({'price': ['min', 'max', 'mean']})

In [108]:
authors_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000

In [109]:
authors_stat.columns = authors_stat.columns.droplevel(0)

In [111]:
authors_stat.rename(columns = {'min':'min_price', 'max':'max_price', 'mean': 'mean_price'}, inplace = True)

In [113]:
authors_stat.reset_index(inplace=True)

In [114]:
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

## Task 5

In [118]:
covers = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price['cover'] = covers

In [119]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [121]:
 ?pd.pivot_table

In [130]:
book_info = pd.pivot_table(values='price',data=authors_price,columns='cover', index='author_name', aggfunc=np.sum, fill_value=0)

In [136]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [132]:
book_info.to_pickle("book_info.pkl")

In [134]:
book_info2 = pd.read_pickle("book_info.pkl")

In [135]:
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950